### ISSUE TITLE
Commit from 3 days ago causes "failed to reach" warnings in rocRAND

### ISSUE THREAD

**Issue by MyNameIsTrez** [ROCm/rocm-docs-core#1030]
Hi, I'm Sander Bos from Stream HPC.

I've assigned myself the internal GitLab issue to resolve the warnings when building the docs of several ROCm projects. I had created a merge request for rocRAND last week that got the number of warnings down to just 1, and I just merged it, but I noticed that some new warnings had suddenly appeared.

After following the lead, it seems that rocRAND queries this rocm-docs-core repository, and commit 40383dd seems to have caused these new warnings. Here is the current build log:
```
...
finished...
doxysphinx v3.3.7
starting build command...
copied 0 resource-files to .../rocRAND/docs/_build/html/doxygen/html
created 0 rst-files in .../rocRAND/docs/doxygen/html
build command done in below 1 second (0:00:00.261433).
doxylink not enabled, skipping setting up the current project
Remote mappings will be fetched from ROCm/rocm-docs-core branch=develop
myst v3.0.1: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions={'html_image', 'substitution', 'colon_fence', 'replacements', 'fieldlist', 'dollarmath'}, disable_syntax=[], all_links_external=False, links_external_new_tab=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, fence_as_directive=set(), number_code_blocks=[], title_to_header=False, heading_anchors=3, heading_slug_func=None, html_meta={}, footnote_transition=True, words_per_minute=200, substitutions={}, linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', enable_checkboxes=False, suppress_warnings=[], highlight_code_blocks=True)
...
loading intersphinx inventory from https://www.sphinx-doc.org/en/master/objects.inv...
loading intersphinx inventory from https://rocm.docs.amd.com/projects/TransferBench/en/latest/objects.inv...
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://rocm.docs.amd.com/projects/rocprofiler-compute/en/latest/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 404 Client Error: Not Found for url: https://rocm.docs.amd.com/projects/rocprofiler-compute/en/latest/objects.inv
intersphinx inventory has moved: https://rocm.docs.amd.com/projects/rocJPEG/en/latest/objects.inv -> https://readthedocs.com/accounts/login/?next=/cas/login%3Fsubproject%3DrocJPEG%26service%3Dhttps%253A%252F%252Frocm.docs.amd.com%252F_%252Faccounts%252Flogin%252F%253Fnext%253Dhttps%25253A%25252F%25252Frocm.docs.amd.com%25252Fprojects%25252FrocJPEG%25252Fen%25252Flatest%25252Fobjects.inv
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://rocm.docs.amd.com/projects/rocJPEG/en/latest/objects.inv' not readable due to ValueError: unknown or unsupported inventory version: ValueError('invalid inventory header: ')
intersphinx inventory has moved: https://rocm.docs.amd.com/projects/rocprofiler-systems/en/latest/objects.inv -> https://readthedocs.com/accounts/login/?next=/cas/login%3Fsubproject%3Drocprofiler-systems%26service%3Dhttps%253A%252F%252Frocm.docs.amd.com%252F_%252Faccounts%252Flogin%252F%253Fnext%253Dhttps%25253A%25252F%25252Frocm.docs.amd.com%25252Fprojects%25252Frocprofiler-systems%25252Fen%25252Flatest%25252Fobjects.inv
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://rocm.docs.amd.com/projects/rocprofiler-systems/en/latest/objects.inv' not readable due to ValueError: unknown or unsupported inventory version: ValueError('invalid inventory header: ')
[autosummary] generating autosummary for: api-reference/cpp-api.rst, api-reference/python-api.rst, conceptual/curand-compatibility.rst, conceptual/data-type-support.rst, conceptual/dynamic_ordering_configuration.rst, conceptual/programmers-guide.rst, doxygen/html/annotated.rst, doxygen/html/annotated_classes.rst, doxygen/html/classes.rst, doxygen/html/classrocrand__cpp_1_1error-members.rst, ..., doxygen/html/rocrandhostcpp_8dox.rst, doxygen/html/structmtgp32__params__fast__t-members.rst, doxygen/html/structmtgp32__params__fast__t.rst, doxygen/html/structrocrand__discrete__distribution__st-members.rst, doxygen/html/structrocrand__discrete__distribution__st.rst, doxygen/html/topics.rst, fortran-api-reference.md, index.rst, install/installing.rst, license.rst
...
```
on the other hand, building rocPRIM locally doesn't have these warnings, even though the logs state it also queries the rocm-docs-core GitHub repository. If you happen to know why it *doesn't* generate the same warnings, I'd love to know:
```
...
finished...
Remote mappings will be fetched from ROCm/rocm-docs-core branch=develop
doxylink not enabled, skipping setting up the current project
myst v3.0.1: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions={'replacements', 'colon_fence', 'fieldlist', 'html_image', 'substitution', 'dollarmath'}, disable_syntax=[], all_links_external=False, links_external_new_tab=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, fence_as_directive=set(), number_code_blocks=[], title_to_header=False, heading_anchors=3, heading_slug_func=None, html_meta={}, footnote_transition=True, words_per_minute=200, substitutions={}, linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', enable_checkboxes=False, suppress_warnings=[], highlight_code_blocks=True)
[autosummary] generating autosummary for: block_ops/data_mov_funcs.rst, block_ops/index.rst, block_ops/ops_classes/adjacent_difference.rst, block_ops/ops_classes/discontinuity.rst, block_ops/ops_classes/exchange.rst, block_ops/ops_classes/histogram.rst, block_ops/ops_classes/index.rst, block_ops/ops_classes/load.rst, block_ops/ops_classes/reduce.rst, block_ops/ops_classes/run_length_decode.rst, ..., thread_ops/thread_search.rst, thread_ops/thread_store.rst, warp_ops/exchange.rst, warp_ops/index.rst, warp_ops/load.rst, warp_ops/reduce.rst, warp_ops/scan.rst, warp_ops/shuffle.rst, warp_ops/sort.rst, warp_ops/store.rst
...
```

Here are the steps I take to build the rocRAND docs:
1. Clone the [rocRAND repository](https://github.com/ROCm/rocRAND), and `cd` into it
2. Download doxygen version 1.9.4 from [here](https://github.com/doxygen/doxygen/releases/tag/Release_1_9_4) (use a newer version of doxygen at your own risk).
3. Run `export PATH=<doxygen 1.9.4 path>/bin:$PATH`
4. Run `doxygen --version` in a new terminal to confirm that your doxygen version is 1.9.4
5. Run `pyenv install 3.10` (using [pyenv](https://github.com/pyenv/pyenv) to manage Python versions)
6. Run `pyenv virtualenv 3.10 venv_rocrand`
7. Run `pyenv activate venv_rocrand`
8. Run `python3 -m pip install -r docs/sphinx/requirements.txt numpy`
9. Run `python3 -m sphinx -T -E -b html -d docs/_build/doctrees -D language=en docs docs/_build/html`
10. Open `docs/_build/html/index.html` in your browser

I'm not sure whether the new warnings are something to be fixed in this rocm-docs-core repository, or in rocRAND. hipCUB, hipRAND, and rocThrust suffer from these same, new warnings as well. Cheers.

**Comment by ppanchad-amd** [comment]
Hi @MyNameIsTrez.  Internal ticket has been created to investigate your issue. Thanks!

**Comment by MyNameIsTrez** [comment]
@ppanchad-amd Thank you! If you could add this to the ticket for me, I'd appreciate it:
These warnings should be caught prematurely by running the documentation generator, sphinx, with the `-W` flag, since that [turns warnings into errors](https://linux.die.net/man/1/sphinx-build).

I was already planning to add this flag to hipCUB, hipRAND, rocPRIM, rocRAND, and rocThrust, but I'm hesitant now, cause I don't want their pipelines to break the moment rocm-docs-core pushes a commit that contains broken URLs.

If rocm-docs-core can promise to check that (at least one of) these other repositories don't suddenly break with a new commit, then I'd love to add the `-W` flag to those repositories their sphinx commands. (Maybe checking for errors in these repositories is already being done by rocm-docs-core, I'm not sure.)

**Comment by jamesxu2** [comment]
Hi @MyNameIsTrez, I've looked into this and I think you won't be able to clean up those downstream warnings without modification to the rocm-docs-core projects.yaml that you linked. This is a task for the rocm-docs-core team to manually clean up (I've forwarded this ticket to them). It's a bit of unfortunate timing that you were cleaning up the warnings in the runup to the ROCm 6.3 release, since there are several newly implemented, renamed and moved projects just added.

I currently see the following links 404'ing:

https://rocm.docs.amd.com/projects/HIP/en/docs/develop
https://rocm.docs.amd.com/projects/omnitrace/en/amd-staging (Renamed to rocprofiler-systems)
https://rocm.docs.amd.com/projects/radeon/en/develop
https://rocm.docs.amd.com/projects/rocJPEG/en/develop (This one is probably just unpublished because it's new)
https://rocm.docs.amd.com/projects/rocprofiler-compute/en/amd-staging (Same as above)
https://rocm.docs.amd.com/projects/rocprofiler-systems/en/amd-staging (Same as above)

> on the other hand, building rocPRIM locally doesn't have these warnings, even though the logs state it also queries the rocm-docs-core GitHub repository. If you happen to know why it doesn't generate the same warnings, I'd love to know:

I don't think rocPRIM really queries the rocm-docs-core repo in the same way as the libraries you're noticing the warnings in. You can see in rocRAND [this section](https://github.com/ROCm/rocRAND/blob/a0d96be01acda6fcde4aed4188b2099dac9abc71/docs/conf.py#L38-L41) which I believe  is invoking those intersphinx calls to link in other projects. rocm-docs-core exports a python module that serves as a baseline for each of these other docs repos, see [here](https://github.com/ROCm/rocm-docs-core/blob/d2d413927d97ac64c2ffcbd2595ca66d26db2b28/src/rocm_docs/projects.py#L459). That section is not present in rocPRIM (which seems like a separate oversight).

> I'm not sure whether the new warnings are something to be fixed in this rocm-docs-core repository, or in rocRAND.

It's not related to rocRAND. 

> These warnings should be caught prematurely by running the documentation generator, sphinx, with the -W flag, since that [turns warnings into errors](https://linux.die.net/man/1/sphinx-build). [...] If rocm-docs-core can promise to check that (at least one of) these other repositories don't suddenly break with a new commit, then I'd love to add the -W flag to those repositories their sphinx commands.

I think this would be a good idea if we could actually prevent errors from rocm-docs-core from poisoning downstream docs builds, but I don't think we can currently make this guarantee. There's a lot of ways these links can break - renaming of a staging branch, renaming of a project, introduction of new projects etc. Sphinx doesn't seem to have a way to filter out certain kinds of errors (-W ~ -Werror), and given the state of rocm-docs-core CI, I think it would be unwise to introduce a build dependency on every downstream docs repo on rocm-docs-core.  

There is an additional, circular-ish dependency problem that appears with forcing -W: If we force -W to build and publish a new project, it will 100% cause a 404ing link because the project is not yet published (i.e. You can't publish your project because it's not published yet, so links to it won't resolve). 

Thanks for the instructions by the way! That made it much easier to reproduce this issue.

**Comment by MyNameIsTrez** [comment]
@jamesxu2 Thank you for the extremely thorough investigation and explanations, I really appreciate it!

I was already wondering why warnings hadn't been turned into errors before I joined a few weeks ago, but now it all makes sense. I guess I'll just manually check for build warnings in the projects every year or so, that should do.

I'm glad to hear the build instructions were satisfactory; I actually copy-pasted them from the merge requests I was already working on that improve the instructions in the READMEs. :)
