### ISSUE TITLE
Allow configuration for documentation for non ROCm sites

### ISSUE THREAD

**Issue by saadrahim** [ROCm/rocm-docs-core#256]

**Comment by domcharrier** [comment]
Below lines result in key errors if a new project has no entry in `rocm_docs/data/projects.yaml` yet.

```python
    mapping_file_loc = "data/projects.yaml"
    mapping_config = importlib_resources.files("rocm_docs") / mapping_file_loc
    with open(mapping_config) as file:
        project_dict = yaml.safe_load(file)

    development_branch = schema_config["$defs"]["project"]["properties"][
        "development_branch"
    ]["default"]
    print(project_dict["projects"][current_project])
```
https://github.com/RadeonOpenCompute/rocm-docs-core/blob/c4e1de5d600a056bb22532b7192029da8084d7e7/src/rocm_docs/projects.py#L289C5-L298C1

Can you suggest a default entry to choose if a project has no entry in that YAML file yet?

Alternatively, could you arrange it that `project_dict` is loaded before `_update_theme_configs` as module variable so that new projects can patch it appropriately?

**Comment by saadrahim** [comment]
- The site title has to be configurable by the project 
- intersphinx
- footer link customization
- javascript that is ROCm only
- Header row
- projects.yaml entry should not be required.

**Comment by samjwu** [comment]
https://github.com/RadeonOpenCompute/rocm-docs-core/pull/284 adds support for "flavors" (i.e.: different theme configurations)
